export const GET_RECIPES = 'GET_RECIPES'
export const GET_RECIPES_REQEUST = 'GET_RECIPES_REQEUST'
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS'
export const GET_RECIPES_FAIL = 'GET_RECIPES_FAIL'